### ISSUE TITLE
Can't extract spectrum data from NIST web page HTML

### ISSUE THREAD

**Issue by ScoobyPorthos** [MKastek/SimulatedLIBS#2]
Hi, 

**Problem Description**

I just install your python package and had the following problem:
`(<class 'IndexError'>, IndexError('list index out of range'), <traceback object at 0x000002435A5CBF40>)`
![image](https://github.com/MKastek/SimulatedLIBS/assets/6832573/b9bb7084-397f-47c8-8bd0-fa8deed7aca1)

The argument passed to the `retrieve_spectrum_from_html` function is the following: _in the attached file for convenience_
[args.txt](https://github.com/MKastek/SimulatedLIBS/files/12303630/args.txt)

**Investiguation**

`retrieve_spectrum_from_html` is called by `retrieve_data_static` sending the 6th `<script>` balise of the page. However, it seems that the HTML layout has changed, as the spectrum data is in another balise

**Solution Suggestion**

Instead of sending a fix index in the `<script>` list, I suggest looking for the balise of interest : 
`list(filter(lambda t: 'var dataDopplerArray' in str(t), soup.find_all("script")))`

Thank you for your package.

**Comment by MKastek** [comment]
Hi,
Thank you very much, I will
solve the problem as soon as possible :).

Best regards,
Marcin Kastek

**Comment by Technophobe01** [comment]
@MKastek Did you get a chance to look at this problem? I see the same problem.

**Comment by MKastek** [comment]
Yes, you can check new version v1.1.0, it should work now: https://pypi.org/project/SimulatedLIBS/
